"""Embed chunked Compileit pages and build a persistent local Chroma index."""

from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings


DEFAULT_CHUNKS_PATH = Path(__file__).parent / "results" / "compileit_chunks" / "chunks.jsonl"
DEFAULT_OUTPUT_DIR = Path(__file__).parent / "results" / "compileit_index"
DEFAULT_COLLECTION_NAME = "compileit_chunks"
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small"


def load_chunk_records(chunks_path: Path) -> list[dict[str, object]]:
    """Load chunk records from the JSONL produced by chunk_pages.py."""

    records: list[dict[str, object]] = []
    with chunks_path.open(encoding="utf-8") as chunks_file:
        for line_number, line in enumerate(chunks_file, start=1):
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(f"Invalid JSON on line {line_number} of {chunks_path}") from error
            if not isinstance(record, dict):
                raise ValueError(f"Expected an object on line {line_number} of {chunks_path}")
            records.append(record)
    return records


def metadata_for_record(record: dict[str, object]) -> dict[str, str | int]:
    """Keep Chroma metadata scalar and retain the fields useful for citations."""

    heading_path = record.get("heading_path", [])
    if not isinstance(heading_path, list):
        heading_path = []

    return {
        "chunk_id": str(record["chunk_id"]),
        "source_url": str(record["source_url"]),
        "canonical_url": str(record["canonical_url"]),
        "page_title": str(record["page_title"]),
        "heading_path": " > ".join(str(part) for part in heading_path),
        "chunk_index": int(record["chunk_index"]),
        "chunk_count": int(record["chunk_count"]),
        "word_count": int(record["word_count"]),
        "source_content_hash": str(record["source_content_hash"]),
    }


def clear_generated_index(output_dir: Path) -> None:
    """Remove only the index artifacts generated by this script."""

    chroma_dir = output_dir / "chroma"
    if chroma_dir.is_symlink():
        raise ValueError(f"Refusing to remove symlinked index directory: {chroma_dir}")
    if chroma_dir.exists():
        shutil.rmtree(chroma_dir)

    manifest_path = output_dir / "index-manifest.json"
    if manifest_path.is_file() or manifest_path.is_symlink():
        manifest_path.unlink()


def build_index(
    chunks_path: Path,
    output_dir: Path,
    collection_name: str,
    embedding_model: str,
) -> dict[str, object]:
    """Build a fresh persistent Chroma index from chunk records."""

    records = load_chunk_records(chunks_path)
    if not records:
        raise ValueError(f"No chunk records found in {chunks_path}")

    for record in records:
        for required_field in ("chunk_id", "embedding_text", "source_url"):
            if required_field not in record:
                raise ValueError(f"Chunk record is missing required field: {required_field}")

    output_dir.mkdir(parents=True, exist_ok=True)
    clear_generated_index(output_dir)

    documents = [
        Document(
            id=str(record["chunk_id"]),
            page_content=str(record["embedding_text"]),
            metadata=metadata_for_record(record),
        )
        for record in records
    ]
    embeddings = OpenAIEmbeddings(model=embedding_model)
    vector_store = Chroma(
        collection_name=collection_name,
        embedding_function=embeddings,
        persist_directory=str(output_dir / "chroma"),
    )
    vector_store.add_documents(documents, ids=[str(record["chunk_id"]) for record in records])

    manifest = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "chunks_path": str(chunks_path),
        "output_dir": str(output_dir),
        "collection_name": collection_name,
        "embedding_model": embedding_model,
        "document_count": len(documents),
        "chunk_ids": [str(record["chunk_id"]) for record in records],
    }
    (output_dir / "index-manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chunks-path", type=Path, default=DEFAULT_CHUNKS_PATH)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--collection-name", default=DEFAULT_COLLECTION_NAME)
    parser.add_argument("--embedding-model", default=DEFAULT_EMBEDDING_MODEL)
    return parser.parse_args()


def main() -> int:
    load_dotenv()
    arguments = parse_args()
    manifest = build_index(
        chunks_path=arguments.chunks_path,
        output_dir=arguments.output_dir,
        collection_name=arguments.collection_name,
        embedding_model=arguments.embedding_model,
    )
    print(
        json.dumps(
            {
                "document_count": manifest["document_count"],
                "embedding_model": manifest["embedding_model"],
                "output_dir": manifest["output_dir"],
            },
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
